windmill/fundo/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from . import views

app_name='fundos'

urlpatterns = [
    path('fechamento/', views.fechamento, name='fechamento'),
    path('base_site/', TemplateView.as_view(template_name='base_site.html'), name='base_site'),
]

windmill/windmill/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views as home_views
from fundo import views as fundo_views
from ativos import views as ativos_views

urlpatterns = [
    path('', home_views.custom_login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('home/', fundo_views.HomePageView.as_view(), name='home'),
    path('home/processos/', include('fundo.urls', namespace='fundos')),
    path('admin/', admin.site.urls, name='cadastro'),
    path('ativos/', include('ativos.urls', namespace='ativos')),
]

windmill/windmill/views.py
from django.contrib.auth import views as auth_views
from django.urls import reverse
from django.http import HttpResponseRedirect

def custom_login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('home'))
    else:
        return auth_views.login(request)

windmill/windmill/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
​
    <!-- Bootstrap CSS -->
    <!-- Latest compiled and minified CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.2.1/flatly/bootstrap.min.css" rel="stylesheet" integrity="sha384-9dACWymWSkhCeCgbjV6xqS20Luu4ue6QnEvr+nMXpPMwIq/OB89AoRh27Flsrxzs" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}" />
    <title>Anima - Windmill</title>
  </head>

  <body>
    {% block content %}{% endblock %}
  </body>
</html>

windmill/windmill/templates/base_site.html
{% extends "base.html" %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="{% url 'home' %}">Anima Windmill</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Placeholder buttons -->
  <div class="navbar-collapse collapse" id="navbarColor01" style="">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Processos de Fundos</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'fundos:fechamento' %}">Fechamento</a>
          <a class="dropdown-item" href="#">Consultar Carteira</a>
          <a class="dropdown-item" href="#">Extrato de Passivo</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Cadastro</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="/admin/ativos">Ativos</a>
          <a class="dropdown-item" href="/admin/fundo">Fundos</a>
          <a class="dropdown-item" href="/admin/mercado">Mercado</a>
          <a class="dropdown-item" href="/admin/calendario">Calendário</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Boletagem de Operações</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="/admin/boletagem/boletaacao/">Ações</a>
          <a class="dropdown-item" href="/admin/boletagem/boletarendafixalocal/">Renda Fixa Local</a>
          <a class="dropdown-item" href="/admin/boletagem/boletarendafixaoffshore/">Renda Fixa Offshore</a>
          <a class="dropdown-item" href="/admin/boletagem/boletafundolocal/">Cotas de Fundo Local</a>
          <a class="dropdown-item" href="/admin/boletagem/boletafundooffshore/">Cotas de Fundo Offshore</a>
          <a class="dropdown-item" href="/admin/boletagem/boletaemprestimo/">Empréstimo de ações</a>
          <a class="dropdown-item" href="/admin/boletagem/boletaprovisao/">Provisões/Despesas</a>
          <a class="dropdown-item" href="/admin/boletagem/boletacpr/">Contas a Pagar/Receber</a>
          <a class="dropdown-item" href="/admin/boletagem/boletacambio/">Câmbio/Transferência de Caixa</a>
          <a class="dropdown-item" href="/admin/boletagem/boletapassivo/">Aporte/Resgate</a>
        </div>
      </li>
    </ul>
    <a class="nav-item" href="{% url 'logout' %}">Log Out</a>
  </div>

</nav>


{% block local %}{% endblock %}
{% endblock %}

windmill/windmill/templates/index.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<div id="content-main">

</div>
{% endblock %}

{% block sidebar %}
<div id="content-related">
    <div class="module" id="recent-actions-module">
        <h2>{% trans 'Recent actions' %}</h2>
        <h3>{% trans 'My actions' %}</h3>
            {% load log %}
            {% get_admin_log 10 as admin_log for_user user %}
            {% if not admin_log %}
            <p>{% trans 'None available' %}</p>
            {% else %}
            <ul class="actionlist">
            {% for entry in admin_log %}
            <li class="{% if entry.is_addition %}addlink{% endif %}{% if entry.is_change %}changelink{% endif %}{% if entry.is_deletion %}deletelink{% endif %}">
                {% if entry.is_deletion or not entry.get_admin_url %}
                    {{ entry.object_repr }}
                {% else %}
                    <a href="{{ entry.get_admin_url }}">{{ entry.object_repr }}</a>
                {% endif %}
                <br/>
                {% if entry.content_type %}
                    <span class="mini quiet">{% filter capfirst %}{{ entry.content_type }}{% endfilter %}</span>
                {% else %}
                    <span class="mini quiet">{% trans 'Unknown content' %}</span>
                {% endif %}
            </li>
            {% endfor %}
            </ul>
            {% endif %}
    </div>
</div>
{% endblock %}