windmill/ativos/urls.py
from django.urls import path, include

from . import views

app_name='ativos'

urlpatterns = [
    #path('', views.ativos_home, name='ativos_home'),
    path('acoes/cadastro', views.AcaoCreateView.as_view(), name='cadastro_acao'),
    path('acoes/', views.AcoesView.as_view(), name='lista_acao'),
    path('acoes/<int:pk>/', views.AcaoDetalheView.as_view(), name='detalhe_acao'),
    path('acoes/<int:pk>/editar', views.AcaoEditarView.as_view(), name='editar_acao'),
    path('acoes/upload_csv', views.UploadCSVAcaoView.as_view(), name='upload_csv_acao'),
]

windmill/fundo/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from . import views

app_name='fundos'

urlpatterns = [
    path('fechamento/', views.fechamento, name='fechamento'),
    path('base_site/', TemplateView.as_view(template_name='base_site.html'), name='base_site'),
]

windmill/windmill/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views as home_views
from fundo import views as fundo_views
from ativos import views as ativos_views

urlpatterns = [
    path('', home_views.custom_login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('home/', fundo_views.HomePageView.as_view(), name='home'),
    path('home/processos/', include('fundo.urls', namespace='fundos')),
    path('admin/', admin.site.urls, name='cadastro'),
    path('ativos/', include('ativos.urls', namespace='ativos')),
]

windmill/ativos/models.py
"""
Modelos deste app servem para armazenar informações que são constantes
sobre ativos financeiros. Informações de mercado, como preço, volatilidade,
etc... serão armazenados no app Mercado.
Responsabilidades deste app:
    - Armazenamento de informações estáticas sobre ativos do mercado.
"""

import datetime
from django.db import models
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericRelation
import fundo.models

# Create your models here.

class Moeda(models.Model):
    nome = models.CharField(max_length=25, unique=True)
    codigo = models.CharField(max_length=3, unique=True)

    class Meta:
        verbose_name_plural = 'Moedas'

    def __str__(self):
        return '%s' % (self.codigo)

class Pais(models.Model):
    nome = models.CharField(max_length=20, unique=True)
    moeda = models.ForeignKey(Moeda, on_delete=models.PROTECT)

    def __str__(self):
        return '%s' % (self.nome)

    class Meta:
        verbose_name_plural = 'Países'

class Ativo(models.Model):
    """
    TODO: CÁLCULO DE RETORNO AJUSTADO A DIVIDENDOS
    """

    nome = models.CharField(max_length=25, unique=True)
    bbg_ticker = models.CharField(max_length=25, unique=True, null=True, blank=True, default=None)
    pais = models.ForeignKey(Pais, on_delete=models.PROTECT, null=True, blank=True)
    # Moeda que representa a apresentação final do ativoself.
    moeda = models.ForeignKey(Moeda, on_delete=models.PROTECT, null=True, blank=True)
    isin = models.CharField(max_length=25, unique=True, null=True, blank=True)
    vertice = GenericRelation('fundo.Vertice')
    descricao = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['nome']
        verbose_name_plural = 'Ativos'

    def __str__(self):
        return '%s' % (self.nome)

    def save(self, *args, **kwargs):
        if self.bbg_ticker == '':
            self.bbg_ticker = None
        super(Ativo, self).save(*args, **kwargs)

    def retorno_do_periodo(self, data_inicio, data_fim, dividendos=False):
        """
        dividendos indica se um ativo deve ser reajustado de acordo com os
        dividendos distribuídos no período.
        """
        import mercado.models as mm
        if dividendos == False:
            preco_inicio = mm.Preco.objects.get(ativo=self, \
                data_referencia=data_inicio)
            preco_fim = mm.Preco.objects.get(ativo=self, data_referencia=data_fim)
            return preco_fim.preco_fechamento/preco_inicio.preco_fechamento - 1
        else:
            return 0

class Renda_Fixa(Ativo):
    TIPO_INFO_CHOICES = (
        ("PU", "PU"),
        ("Yield", "Yield")
    )
    vencimento = models.DateField(default=datetime.date.max)
    cupom = models.DecimalField(max_digits=7, decimal_places=5, null=True,
        default=0)
    info = models.CharField("informação de mercado", max_length=5,
        choices=TIPO_INFO_CHOICES, default="PU")
    periodo = models.IntegerField("periodicidade do cupom em meses", default=0)

    class Meta:
        verbose_name_plural = 'Ativos de Renda Fixa'

class Acao(Ativo):
    TIPO_CHOICES=(
        ("PN", "PN"),
        ("ON", "ON"),
        ("ADR", "ADR"),
        ("Unit", "Unit"),
        ("Direito de Subscrição", "Direito de Subscrição"),
        ("Recibo de Subscrição", "Recibo de Subscrição")
    )

    tipo = models.CharField(max_length=21, choices=TIPO_CHOICES, null=True)

    class Meta:
        verbose_name_plural = 'Ações'

    def get_absolute_url(self):
        return reverse('ativos:detalhe_acao', args=[str(self.id)])

class Cambio(Ativo):
    """
    Não é um ativo em si, mas como possui valor (taxa de conversão entre
    moedas) diário, decidimos caracterizá-lo como tal para facilitar.
    """

    moeda_origem = models.ForeignKey(Moeda, on_delete=models.PROTECT,
        null=False, blank=False, related_name='cambio_moeda_origem')
    moeda_destino = models.ForeignKey(Moeda, on_delete=models.PROTECT,
        null=False, blank=False, related_name='cambio_moeda_destino')

    class Meta:
        verbose_name_plural = 'Câmbios'

class Caixa(Ativo):

    # Indica a moeda do caixa
    custodia = models.ForeignKey('fundo.Custodiante', on_delete=models.PROTECT)
    corretora = models.ForeignKey('fundo.Corretora', on_delete=models.PROTECT)

    class Meta:
        verbose_name_plural = "Caixas"

class Fundo_Local(Ativo):

    CNPJ = models.CharField(max_length=18, null=True, blank=True)
    # Indica quanto tempo depois do pedido a cotização de um resgate é feita
    data_cotizacao_resgate = models.DurationField(null=True, blank=True)
    # Indica quanto tempo depois do pedido a liquidação de um resgate é feita
    data_liquidacao_resgate = models.DurationField(null=True, blank=True)
    # Indica quanto tempo depois do pedido a cotização de uma aplicação é feita
    data_cotizacao_aplicacao = models.DurationField(null=True, blank=True)
    # Indica quanto tempo depois do pedido a liquidação de uma aplicação é feita
    data_liquidacao_aplicacao = models.DurationField(null=True, blank=True)
    banco = models.CharField(max_length=3, null=True, blank=True)
    agencia = models.CharField(max_length=6, null=True, blank=True)
    conta_corrente = models.CharField(max_length=7, null=True, blank=True)
    digito = models.CharField(max_length=1, null=True, blank=True)
    conta_cetip = models.CharField(max_length=10, null=True, blank=True)
    codigo_cetip = models.CharField(max_length=10, null=True, blank=True)
    # Liga o ativo fundo ao fundo do ponto de vista de gestão.
    gestao = models.ForeignKey('fundo.Fundo', on_delete=models.PROTECT, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Fundos Locais'

    def gerido(self):
        if self.gestao == None:
            return False
        return self.gestao.gestora.anima

class Fundo_Offshore(Ativo):

    data_cotizacao_resgate = models.DurationField(null=True,blank=True)
    data_liquidacao_resgate = models.DurationField(null=True,blank=True)
    data_cotizacao_aplicacao = models.DurationField(null=True,blank=True)
    data_liquidacao_aplicacao = models.DurationField(null=True,blank=True)
    gestao = models.ForeignKey('fundo.Fundo', on_delete=models.PROTECT, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Fundos Offshore'

    def gerido(self):
        return self.gestao.gestora.anima

windmill/ativos/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.admin.widgets import RelatedFieldWidgetWrapper
from django.contrib import admin
from .models import Acao, Pais, Moeda, Ativo


class AcaoForm(ModelForm):
    pais = forms.ModelChoiceField(queryset=Pais.objects.all(), required=False)

    def __init__(self, *args, **kwargs):
        super(AcaoForm, self).__init__(*args, **kwargs)
        add_related_field_wrapper(self, 'pais')

    class Meta:
        model = Acao
        fields = "__all__"

class AcaoCSVForm(forms.Form):
    file = forms.FileField()

def add_related_field_wrapper(form, col_name):
    rel_model = form.Meta.model
    rel = rel_model._meta.get_field(col_name).remote_field
    form.fields[col_name].widget = RelatedFieldWidgetWrapper(
    form.fields[col_name].widget, rel, admin.site, can_add_related=True,
    can_change_related=False)

class AtivoForm(forms.ModelForm):
    class Meta:
        model = Ativo
        fields = "__all__"
    def clean_bbg_ticker(self):
        return self.cleaned_data['bbg_ticker'] or None

windmill/ativos/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, FormView

from .models import Acao
from .forms import AcaoForm, AcaoCSVForm

def ativos_home(request):
    return HttpResponse('<html><title>Cadastro de ativos</title></html>')

def acoes(request):
    acoes = Acao.objects.all()
    return render(request,
        'acoes/cadastro.html',
        {'acoes':acoes})

class CadastroAcaoView(FormView):
    form_class = AcaoForm
    template_name = 'acoes/cadastro.html'
    fields = '__all__'

class AcoesView(ListView):
    model = Acao
    template_name ='acoes/lista.html'

class AcaoEditarView(UpdateView):
    model = Acao
    template_name = 'acoes/editar.html'
    fields = "__all__"

class AcaoDetalheView(DetailView):
    model = Acao
    template_name = 'acoes/detalhe.html'

class UploadCSVAcaoView(FormView):
    form_class = AcaoCSVForm
    template_name = 'acoes/cadastro.html'
    fields = '__all__'

class AcaoCreateView(CreateView):
    model = Acao
    template_name = 'acoes/form.html'

windmill/ativos/templates/acoes/cadastro.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block content %}
<h2>Cadastro de ações</h2>
<div class="d-flex p-2">
  <form action="" method="post">
    {% for hidden_field in form.hidden_fields %}
      {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
          {{ error }}
        {% endfor %}
      </div>
    {% endif %}

    {% for field in form.visible_fields %}
      <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
          {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
            {% render_field field class="form-control is-valid" %}
          {% endif %}
        {% else %}
          {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">Enviar</button>
  </form>
</div>
<div>
  <form method="post" enctype="multipart/form-data">
    <div class="form-group">
      {% csrf_token %}
      <p class="h4">Cadastrar ações por arquivo .csv</p>
      <input type="file" name="Importar .csv" class="form-control">
      <button type="submit" class="btn btn-primary">Upload</button>
    </div>

  </form>
</div>
{% endblock %}

windmill/ativos/templates/acoes/detalhe.html
{% extends 'base.html' %}

{% block content %}
<h3>Ação</h3>
<div class="registro-acao">
  <p>Nome: {{ object.nome }}</p>
  <p>Ticker Bloomberg: {{ object.bbg_ticker }}</p>
  <p>País: {{ object.pais }}</p>
  <p>Tipo: {{ object.tipo }}</p>
</div>

<a href="{% url 'ativos:editar_acao' acao.pk %}">+ Editar ação</a>

{% endblock %}

windmill/ativos/templates/acoes/editar.html
{% extends 'base.html '%}

{% block content %}
<h3>Editar ação</h3>
<form action="" method="post">
  {% csrf_token%}
  {{ form.as_p }}
  <input type="submit" value="Editar">
</form>
{% endblock %}

windmill/ativos/templates/acoes/form.html
{% extends 'base_site.html'%}

{% block local %}
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-success">Salvar</button>
  </form>
{% end block %}

windmill/ativos/templates/acoes/lista.html
{% extends 'base.html' %}
{% block content%}
  <h1>Lista de Ações</h1>
  <ul>
    {% for acao in object_list %}
    <li>
      <a href="{{ acao.get_absolute_url }}">{{ acao }}</a>
    </li>
    {% endfor %}
  </ul>
{% endblock %}